### ISSUE TITLE
Error building PrivateWebSite

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/BikeSharing360_Websites#2]
Hi,

I tried building PrivateWebSite using VS 2017 RC. I get the following error. Can anyone help me with this?
![1](https://cloud.githubusercontent.com/assets/13433045/21585677/3ab899f2-d0bd-11e6-90fe-46448c3d06bd.png)

**Comment by herbat73** [comment]
Same on my VS2017 RC Referesh. It looks project properites is not setup correctly and point to Core 1.1 framework.  In the result NuGet packages are not downloaded.  I tried to setup manually but it leads but so far no luck.  It leads me to many conflicts with nuget libs.

**Comment by eiximenis** [comment]
Hi to everyone.
Project was working fine int the 1st RC of VS2017 (the one used in Connect). We are experiencing issues with newer RCs of Visual Studio 2017. 
Once the RC3 of VS2017 is publicly available, we will release updated projects that hopefully will solve all these issues.

Thanks!

**Comment by SKApretto71** [comment]
Thanks for letting us know.
Have you any ETA for RC3 to be published and available (months or weeks, not asking for commitment)

**Comment by SKApretto71** [comment]
As I'm getting the same error for the Public site as well - the one on MVC Core, not the standard MVC5 - is this related to the same or the others are expected to work?

**Comment by SrivatsaMarichi** [comment]
The project works fine now with VS 2017
