### ISSUE TITLE
Not compatible with Bootstrap v4 release 6

### ISSUE THREAD

**Issue by StefanKert** [Microsoft/BikeSharing360_Websites#3]
When running _npm run build_ following error occures. 

![image](https://cloud.githubusercontent.com/assets/7176615/21740982/08a24844-d4ca-11e6-873d-035f86bd7d34.png)

The reason for this error is, that in _package.json_, the reference to bootstrap is defined as the following.

` "bootstrap": "^4.0.0-alpha.5",`

Because of the defined logic for ^ the used package is always the last working package (non breaking Version). The latest version for bootstrap package currently is 4.0.0-alpha.6. The difference between the two versions consists of some files beeing renamed. For the PrivateWebsite this results in an error when performing the command above, because these two packages got renamed

- _animation.scss -> _transitions.scss [#21370](https://github.com/twbs/bootstrap/pull/21370)
- _tags.scss -> _badge.scss [#21020](https://github.com/twbs/bootstrap/pull/21020) 

The wrong references are defined in [scss/vendor/_bootstrap.scss](https://github.com/Microsoft/BikeSharing360_Websites/blob/master/PrivateWebSite/src/BikeSharing_Private_Web_Site/src/scss/vendor/_bootstrap.scss).

There are two possible solutions. 

1. Change reference to bootstrap package in package.json to use specific version 
`` "bootstrap": "4.0.0-alpha.5",``
2. Change references _scss/vendor/_bootstrap.scss_ to use correct filenames.

I would suggest to use solution 2. because it will fit up to future relases of bootstrap as well as the final release of bootstrap. So for this purpose I am doing a pull request that fixes this issue.

Cheers

**Comment by eiximenis** [comment]
PR #4 merged.

I close the issue.
Thanks!
