### ISSUE TITLE
Hosting environment on Azure

### ISSUE THREAD

**Issue by SKApretto71** [Microsoft/BikeSharing360_Websites#5]
Assuming I want to host those sites on Azure, what woudl be the hosting service I need to use? Are those running under IIS or any other runtime like node.js? Looking to the solutions I'm bit confused by the usage of csproj together with gulp and .Net Code.

I'm a newby, some basic guidance to run the cose would be appreciated.

**Comment by eiximenis** [comment]
Hi @SKApretto71 
PublicWebSite is a MVC5 standard app, so must use IIS (or standard website in Azure)
PrivateWebSite and PublicWebSite_NetCore are MVC Core applications, so technically can be hosted in any netcore valid server. You can use IIS or standard website in Azure.

No one of these websites uses nodejs.

Thanks!

**Comment by SKApretto71** [comment]
Thanks. I'm looking to the .Net Core applications specifically, hence MVC Core. THe project is not building out the usual directory with web.config, dir\ folder with Dlls and such standard artifacts/content, here my question as I was seeying lot of JS and Gulp, usually bound to node.js

Can you share how the published package should look like (what to include)? Locally it build fine on my 2017 RC, but the F5/debug is not getting anything up

**Comment by SKApretto71** [comment]
I was able - with the new code - to run on Azure. Closing.
